import {
  AccidenteTrabajo,
  CampamentoHabitacion,
  EntregaBeneficio,
  SolicitudAprobacion,
  UnitTenant,
  ResilienceMetrics,
} from '../types';
import { encryptAES256 } from './securityCrypto';

export const INITIAL_UNIT_TENANTS: UnitTenant[] = [
  { id: 'ten-01', name: 'Sede Morococha - Unidad Toromocho', code: 'MOR-TOR', location: 'Yauli, Junín', activeWorkersCount: 450 },
  { id: 'ten-02', name: 'Sede Huaraucaca - Unidad Atacocha', code: 'HUA-ATA', location: 'Pasco, Pasco', activeWorkersCount: 320 },
  { id: 'ten-03', name: 'Sede San Cristóbal - Unidad Carahuacra', code: 'SCR-CAR', location: 'Yauli, Junín', activeWorkersCount: 280 },
  { id: 'ten-04', name: 'Sede Huayhuay - Planta Concentradora', code: 'HUA-PLA', location: 'Yauli, Junín', activeWorkersCount: 190 },
];

export const INITIAL_ACCIDENTES_TRABAJO: AccidenteTrabajo[] = [
  {
    idAccidente: 'ACC-09-001',
    idTrabajador: 'W001',
    workerName: 'Juan Pérez Quispe',
    workerDni: '45871236',
    fechaSiniestro: '2026-07-15 10:30',
    lugarAccidente: 'Socavón Nivel 420 - Mina Subterránea',
    gravedad: 'Incapacitante Temporal',
    tipoAccidente: 'Trabajo Directo',
    numFormularioST7: 'ST7-2026-89541',
    diasIncapacidad: 35,
    sueldoPromedio12Meses: 3600,
    subsidioEmpresaDias: 20,
    subsidioEmpresaMonto: 2400,
    subsidioEssaludDias: 15,
    subsidioEssaludMonto: 1800,
    estadoViva: 'En Tramitación VIVA',
    cie10Codigo: 'S82.1 - Fractura de tibia proximal',
    cie10DiagnosticoEncrypted: encryptAES256('S82.1 - Fractura de tibia proximal durante maniobra de acople'),
    unidadMinera: 'Sede Morococha - Unidad Toromocho',
  },
  {
    idAccidente: 'ACC-09-002',
    idTrabajador: 'W002',
    workerName: 'María Rodríguez Fernández',
    workerDni: '71234567',
    fechaSiniestro: '2026-07-28 07:15',
    lugarAccidente: 'Carretera de Acceso Campamento Moro-Planta',
    gravedad: 'Leve',
    tipoAccidente: 'Accidente de Trayecto',
    numFormularioST7: 'ST7-2026-90112',
    diasIncapacidad: 12,
    sueldoPromedio12Meses: 3000,
    subsidioEmpresaDias: 12,
    subsidioEmpresaMonto: 1200,
    subsidioEssaludDias: 0,
    subsidioEssaludMonto: 0,
    estadoViva: 'Generado',
    cie10Codigo: 'S93.4 - Esguince del tobillo',
    cie10DiagnosticoEncrypted: encryptAES256('S93.4 - Esguince de tobillo por caída al descender del bus de trasbordo'),
    unidadMinera: 'Sede Morococha - Unidad Toromocho',
  },
];

export const INITIAL_CAMPAMENTO_HABITACIONES: CampamentoHabitacion[] = [
  {
    idAsignacion: 'CAM-10-101',
    idTrabajador: 'W001',
    workerName: 'Juan Pérez Quispe',
    workerDni: '45871236',
    company: 'ECOSEM PUCARA',
    moduloHabitacion: 'Módulo A - Pabellón Minero 01',
    camaAsignada: 'Cama A-101',
    fechaIngreso: '2026-08-01',
    fechaSalida: '2026-08-15',
    estadoHabitacion: 'Limpia / Asignada',
    registroLavandería: '2026-08-05 (Sábanas y edredón térmico sanitizados)',
    pagoHigieneEstado: 'Conforme',
    unidadMinera: 'Sede Morococha - Unidad Toromocho',
  },
  {
    idAsignacion: 'CAM-10-102',
    idTrabajador: 'W002',
    workerName: 'María Rodríguez Fernández',
    workerDni: '71234567',
    company: 'CONTRATISTAS MINEROS SAC',
    moduloHabitacion: 'Módulo B - Pabellón Damas 02',
    camaAsignada: 'Cama B-204',
    fechaIngreso: '2026-08-03',
    fechaSalida: '2026-08-17',
    estadoHabitacion: 'Revisión Lavandería',
    registroLavandería: '2026-07-28',
    pagoHigieneEstado: 'Conforme',
    unidadMinera: 'Sede Morococha - Unidad Toromocho',
  },
];

export const INITIAL_ENTREGAS_BENEFICIOS: EntregaBeneficio[] = [
  {
    idEntrega: 'ENT-11-501',
    idTrabajador: 'W001',
    workerName: 'Juan Pérez Quispe',
    workerDni: '45871236',
    tipoBeneficio: 'Kit Navideño / Panetón',
    fechaEntrega: '2026-08-02 14:00',
    firmaDigitalUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    estadoEntrega: 'Entregado y Firmado',
    observaciones: 'Conforme. Entregado en Almacén Central de Bienestar Social.',
    unidadMinera: 'Sede Morococha - Unidad Toromocho',
  },
  {
    idEntrega: 'ENT-11-502',
    idTrabajador: 'W002',
    workerName: 'María Rodríguez Fernández',
    workerDni: '71234567',
    tipoBeneficio: 'Kit Escolar Hijos',
    fechaEntrega: '2026-08-06 09:30',
    firmaDigitalUrl: '',
    estadoEntrega: 'Pendiente de Recojo',
    observaciones: 'Pendiente apersonamiento del titular.',
    unidadMinera: 'Sede Morococha - Unidad Toromocho',
  },
];

export const INITIAL_SOLICITUDES_APROBACIONES: SolicitudAprobacion[] = [
  {
    idSolicitud: 'SOL-12-001',
    idTrabajador: 'W001',
    workerName: 'Juan Pérez Quispe',
    workerDni: '45871236',
    tipoSolicitud: 'Auxilio por Defunción',
    monto: 3500,
    nivelAprobacion1: 'Aprobado RRHH',
    aprobador1User: 'Jefe RRHH - Lic. Carlos Mota',
    fechaAprobacion1: '2026-08-04 11:00',
    nivelAprobacion2: 'Aprobado Gerencia',
    aprobador2User: 'Gerencia General ECOSEM',
    fechaAprobacion2: '2026-08-04 16:30',
    estadoWorkflow: 'Aprobado y Desembolsado',
    documentoRespaldoUrl: 'acta_defuncion_validada.pdf',
    unidadMinera: 'Sede Morococha - Unidad Toromocho',
  },
  {
    idSolicitud: 'SOL-12-002',
    idTrabajador: 'W002',
    workerName: 'María Rodríguez Fernández',
    workerDni: '71234567',
    tipoSolicitud: 'Activación Seguro Vida Ley',
    monto: 50000,
    nivelAprobacion1: 'Aprobado RRHH',
    aprobador1User: 'Jefe RRHH - Lic. Carlos Mota',
    fechaAprobacion1: '2026-08-07 09:00',
    nivelAprobacion2: 'Pendiente',
    estadoWorkflow: 'En Revisión Gerencia',
    documentoRespaldoUrl: 'expediente_vida_ley.pdf',
    unidadMinera: 'Sede Morococha - Unidad Toromocho',
  },
];

export const INITIAL_RESILIENCE_METRICS: ResilienceMetrics = {
  rpoMinutes: 15,
  rtoMinutes: 8,
  lastBackupTimestamp: new Date().toISOString().replace('T', ' ').substring(0, 16),
  nodeStatus: 'Primary (Morococha Node 01)',
  isFailoverActive: false,
  encryptedS3Bucket: 's3://ecosem-bienestar-backups-aes256-prod',
};
